# Generated by Django 4.0.4 on 2022-05-09 12:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20210204_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
